services:
  - type: web
    name: wnbaedge-backend
    env: node
    buildCommand: npm install
    startCommand: node API/server.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/test

  - type: web
    name: wnbaedge-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server-frontend.js
    envVars:
      - key: REACT_APP_API_URL
        sync: false
        value: https://wnbaedge.onrender.com/api
      - key: NODE_ENV
        value: production
